### DISCUSSION TITLE
Using with ESPHome?

### DISCUSSION THREAD

**Discussion by stas-sl** [mathieucarbou/ESPAsyncWebServer#114] [Q&A]
Hi, thanks for maintaining this library!

I'm wondering what the best way is to integrate it with ESPHome. I noticed some discussions about it, but I couldn't find a clear guide on what’s needed to get it working. Can it serve as a drop-in replacement for ESPAsyncWebServer-esphome?

I spent a few hours wrestling with PIO dependency management, and I think I've finally got it working. I'll share my solution here, but if there's a better approach, I’d love to know!

So I ended up with:

```yaml
esphome:
  platformio_options:

    # that's important, as by default it is set to 'off', 
    # which can lead to missing dependencies.
    lib_ldf_mode: chain 

    # that's also important, as without it both libraries will be included, 
    # which will result in duplicate symbols
    lib_ignore:
      - ESPAsyncWebServer-esphome
  libraries:
    - mathieucarbou/ESPAsyncWebServer @ 3.3.7
```
Maybe there is a way to avoid setting `lib_ldf_mode: chain`? I'm unsure what potential downsides might be.

Solution that didn't work for me, though it is mentioned in ESPHome documentation as a way to override some libraries:
```yaml
esphome:
  libraries:
    - ESPAsyncWebServer-esphome=mathieucarbou/ESPAsyncWebServer @ 3.3.7
```

I haven't thoroughly tested it yet, but it compiles and works so far. Hopefully, it will be more stable than ESPHome's fork.

**Comment by mathieucarbou** [comment]
Good question!

And I do not know the answer. Since ESPAsyncWebServer is used internally to make esphome work, I am not sure that you can replace it with the lib option (which is meant to add additional libraries).

But It should be compatible since the API is the same and based on the same original fork. If you happen to see some differences,, please let me know.

Also, pay attention that ESPAsyncWebServer is not the only dependency: ESPAsyncWebServer also have some dependencies (e.g. AsyncTCP for ESP32), and the AsyncTCP lib ESPHome is using also misses some bug-fixes.

**Comment by stas-sl** [comment]
Mathieu, thanks for your response.

I've found some discussions why they decided to turn off PIO's LDF and specify all dependencies manually instead. Setting `lib_ldf_mode: chain` worked for me, but maybe it could cause issues with other components, as mentioned in these discussions:
https://discord.com/channels/429907082951524364/1089875019326300250
https://github.com/esphome/esphome/pull/2435
https://github.com/esphome/esphome/pull/2608

It seems it's better to keep it turned off. Fortunately, making it work is simple once you understand that the order of specifying dependencies is crucial! If you disable LDF, you need to declare dependencies before the libraries that rely on them. 

So, now my working config looks like this:

```yaml
esphome:
  platformio_options:
    lib_ignore:
      - AsyncTCP-esphome
      - ESPAsyncWebServer-esphome
  libraries:
    - FS
    - WiFi
    - Update
    - mathieucarbou/ESPAsyncWebServer @ 3.3.7
```

Strangely, even after adding those libraries to lib_ignore, they're still being downloaded:

```
Library Manager: Installing esphome/AsyncTCP-esphome @ 2.1.4
INFO Installing esphome/AsyncTCP-esphome @ 2.1.4
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@2.1.4 has been installed!
INFO AsyncTCP-esphome@2.1.4 has been installed!
Library Manager: Installing mathieucarbou/AsyncTCP @ 3.2.5
INFO Installing mathieucarbou/AsyncTCP @ 3.2.5
Unpacking  [####################################]  100%
Library Manager: AsyncTCP@3.2.5 has been installed!
INFO AsyncTCP@3.2.5 has been installed!
Library Manager: Installing mathieucarbou/ESPAsyncWebServer @ 3.3.7
INFO Installing mathieucarbou/ESPAsyncWebServer @ 3.3.7
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer@3.3.7 has been installed!
INFO ESPAsyncWebServer@3.3.7 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 3.2.2
INFO Installing esphome/ESPAsyncWebServer-esphome @ 3.2.2
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@3.2.2 has been installed!
INFO ESPAsyncWebServer-esphome@3.2.2 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
```

<img width="348" alt="image" src="https://github.com/user-attachments/assets/cd5d7102-6220-4724-b97a-dcda8831b581">

However, they are not mentioned later in Dependency Graph:

```
Dependency Graph
|-- FS @ 2.0.0
|-- WiFi @ 2.0.0
|-- Update @ 2.0.0
|-- AsyncTCP @ 3.2.5
|-- ESPAsyncWebServer @ 3.3.7
|-- ESPmDNS @ 2.0.0
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
```

In contrast to when they're not added to `lib_ignore`, both libraries are still mentioned, and I encounter multiple compilation errors.

```
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- FS @ 2.0.0
|-- WiFi @ 2.0.0
|-- Update @ 2.0.0
|-- AsyncTCP @ 3.2.5
|-- ESPAsyncWebServer @ 3.3.7
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- ESPmDNS @ 2.0.0
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
```

As I mentioned, this version compiles and performs significantly better than the original `ESPAsyncWebServer-esphome`. I’ve tested it on two heavily loaded devices with similar configurations. Both of them run CPU-intensive audio processing that keeps a single core busy about 90% of the time. Though one of them besides it also has Bluetooth stack enabled, which leaves only 70-80 KB of free memory.

Previously, it was nearly impossible to open the ESPHome's Web server UI on either device because the server would initially send a lot of data, including all sensor information, and continue updating every second. Even if you managed to open it, refreshing the page a few times would inevitably crash the server.

Now, after switching to your fork, I haven’t experienced a single crash on the device without Bluetooth, which has more free RAM. However, I still get some crashes on the device with Bluetooth and less available memory, but it’s much more stable overall. Maybe I should tune some parameters you mentioned in the README, like CONFIG_ASYNC_TCP_STACK_SIZE or something similar. I wonder if 70 KB of free RAM is too low...

However, it's probably still too early to draw conclusions. I'll continue monitoring the stability and see how it performs over time.
